### ISSUE TITLE
Бесконечная рекурсия

### ISSUE THREAD

**Issue by atakajlo** [yiimaker/yii2-translatable#2]
Если свойство в моделе, к которой прикреплено это поведение, не найдено, то возникает бесконечная рекурсия из-за обращения к методу canGetProperty, который в итоге вызывает сам себя.

https://github.com/yiimaker/yii2-translatable/blob/master/src/TranslatableBehavior.php#L192
https://github.com/yiimaker/yii2-translatable/blob/master/src/TranslatableBehavior.php#L201

Как было в оригинальном расширении:

https://github.com/creocoder/yii2-translateable/blob/master/src/TranslateableBehavior.php#L148
https://github.com/creocoder/yii2-translateable/blob/master/src/TranslateableBehavior.php#L156

В таком случае все прекрасно работает

**Comment by greeflas** [comment]
@atakajlo Ошибка исправлена. Большое спасибо за ваш фидбек!
